#!/bin/bash

function ssh_nocheck {
    ssh -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' "$@"
}
dir="/home/linmin/project/run/tensorboard/"
ssh_nocheck -p$SLURM_PORT localhost "rm -r $dir/*"