#!/bin/bash

source $(dirname $0)/argparse "$@" || exit 1
source $(dirname "$0")/utils.sh || exit 1

SLURM_PORT=$(find_port "$CLUSTER")
$(dirname $0)/connect "$CLUSTER"

dir="~/project/run/tensorboard/"
ssh_nocheck -p"$SLURM_PORT" "$USER"@localhost "rm -r $dir/*"
