#!/bin/bash
if [ -z $SLURM_PORT ]
then
    echo "Make a connection first"
    exit 1
fi
function ssh_nocheck {
    ssh -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' "$@"
}
ssh_nocheck -p$SLURM_PORT localhost "sacct --starttime 2019-10-25 -u linmin --format=Jobid,Jobname%-50 --allocations -n"
