#!/usr/bin/env bash

source $(dirname $0)/argparse "$@" || exit 1
source $(dirname "$0")/slurm_utils.sh || exit 1

SLURM_PORT=$(find_port "$CLUSTER")
$(dirname $0)/slurm_connect "$CLUSTER"

ssh_nocheck -p$SLURM_PORT $USER@localhost 'bash -'