#!/bin/bash

source $(dirname $0)/argparse "$@" || exit 1
source $(dirname "$0")/slurm_utils.sh || exit 1

$(dirname "$0")/remote_run "$CLUSTER" <<EOF
mkdir -p ~/project/run/tar
mkdir -p ~/project/run/untar
mkdir -p ~/project/run/tensorboard

module load python/3.7
module load cuda/10.0
module load cudnn/7.6

virtualenv ~/tf2
source ~/tf2/bin/activate
pip install tensorboard tensorflow-gpu tensorflow_probability tqdm ipython tensorflow_datasets tensorflow_metadata scipy matplotlib h5py cython

EOF
