#!/usr/bin/env bash

source $(dirname $0)/argparse "$@" || exit 1
source $(dirname $0)/slurm_utils.sh || exit 1

INFO="$(find_all "$CLUSTER")"
INFO=($INFO)
LOCALPORT=${INFO[0]}
HOSTNAME=${INFO[1]}
REMOTEPORT=${INFO[2]}
USERNAME=${INFO[3]}

if [ -z "$(pgrep -f "\-L $LOCALPORT:localhost:$REMOTEPORT")" ]
then
    echo "Launching a background ssh session to $HOSTNAME" >> /dev/stderr
    nohup bash -c "ssh -n -p $REMOTEPORT -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' -tt -L $LOCALPORT:localhost:$REMOTEPORT $USER@$HOSTNAME" &> /dev/null &
    echo "Waiting connection to $USER@$HOSTNAME" >> /dev/stderr
    while [ -z "$(lsof -i -P -n | grep "$LOCALPORT")" ]
    do
	sleep 1
    done
    echo "connection established" >> /dev/stderr
else
    while [ -z "$(lsof -i -P -n | grep "$LOCALPORT")" ]
    do
	sleep 1
    done
    echo "$CLUSTER through localhost:$LOCALPORT" >> /dev/stderr
fi
