#!/usr/bin/env bash

source $(dirname $0)/argparse "$@" || exit 1
source $(dirname "$0")/slurm_utils.sh || exit 1

INFO="$(find_all "$CLUSTER")"
INFO=($INFO)
LOCALPORT=${INFO[0]}
HOSTNAME=${INFO[1]}
REMOTEPORT=${INFO[2]}
USERNAME=${INFO[3]}
VIRTUALENV=${INFO[4]}

$(dirname $0)/slurm_connect "$CLUSTER"

pack_result="$(VIRTUALENV=$VIRTUALENV "$(dirname $0)"/slurm_pack "${_arg_leftovers[@]}")"
pack_result=($pack_result)
if [ $? -eq 0 ]; then
    echo "pack tarball success" >> /dev/stderr
else
    echo "pack tarball failed" >> /dev/stderr
    exit 1
fi
tarball=${pack_result[0]}
workdir=${pack_result[1]}
echo "tarball stored at $tarball" >> /dev/stderr

echo "Uploading $tarball to server" >> /dev/stderr
scp -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' -P$LOCALPORT /tmp/$tarball $USER@localhost:~/project/run/tar/
if [ $? -eq 0 ]; then
    echo "Upload success" >> /dev/stderr
else
    echo "Upload failed" >> /dev/stderr
    exit 1
fi

if [ -z "$SLURMTRACK" ]; then
    ssh_nocheck -p$SLURM_PORT $USER@localhost "tar xf ~/project/run/tar/$tarball -C ~/project/run/untar && cd ~/project/run/untar/$workdir && sbatch ./sbatch_script.sh"
else
    ssh_nocheck -p$SLURM_PORT $USER@localhost "tar xf ~/project/run/tar/$tarball -C ~/project/run/untar && cd ~/project/run/untar/$workdir && sbatch ./sbatch_script.sh && tail -F ~/project/run/untar/$workdir/slurm.err"
fi
