#!/usr/bin/env bash

source $(dirname "$0")/argparse "$@" || exit 1
source $(dirname "$0")/slurm_utils.sh || exit 1
SLURM_PORT=$(find_port "$CLUSTER")
$(dirname $0)/slurm_connect "$CLUSTER"

if [ -t 1 ] # if executed without pipe
then
    ssh_nocheck -p"$SLURM_PORT" "$USER"@localhost "sacct --starttime 2019-10-25 -u $USER --format=Jobid,Jobname%-50 --allocations -n" | grep --color "${_arg_leftovers[@]}"
else
    ssh_nocheck -p"$SLURM_PORT" "$USER"@localhost "sacct --starttime 2019-10-25 -u $USER --format=Jobid,Jobname%-50 --allocations -n" | grep "${_arg_leftovers[@]}" | cut -d ' ' -f1
fi
