#!/usr/bin/env python3
import logging
logging.basicConfig(level=logging.INFO, format='%(message)s')
from git import Repo
from git.cmd import Git
from datetime import datetime
import uuid
import tarfile
import argparse
import sys


def parse_sbatch_args(args):
  sbatch_args = {}
  while len(args) > 0:
    arg = args[0]
    if arg.startswith('--') and '=' in arg:
      arg = args.pop(0)
      key, value = arg.split('=')
      sbatch_args[key] = value
    elif arg.startswith('--') and '=' not in arg:
      key = args.pop(0)
      value = args.pop(0)
      sbatch_args[key] = value
    elif arg.startswith('-'):
      key = args.pop(0)
      if not args[0].startswith('-'):
          value = args.pop(0)
      else:
          value = ''
      sbatch_args[key] = value
    else:
      break
  return sbatch_args, args


def sbatch_script(options, commands, sbatch_script_name, verbose=True):
  options.update({
      "--output": "slurm.out",
      "--error": "slurm.err",
  })
  def print_if_verbose(*args, **kwargs):
    if verbose:
      logging.info(*args, **kwargs)
  with open(sbatch_script_name, "w") as f:
    f.write("#!/bin/bash\n")
    for k, v in options.items():
      f.write(f"#SBATCH {k} {v}\n")
    for command in commands:
      f.write(f"{command}\n")
  with open(sbatch_script_name, "r") as f:
    print_if_verbose(f.read())


def pack(job_name, command, sbatch_args):
  # check if the repo is clean
  repo = Repo("./", search_parent_directories=True)
  git_cmd = Git("./")
  diff = repo.index.diff(None)
  timestamp = datetime.now().strftime('%Y%m%d.%H%M%S')
  exec_path = git_cmd.rev_parse(show_prefix=True)
  if len(diff) > 0:
    repo.git.add('-u')
    repo.index.commit(f"[dirty] commit {timestamp}")
    tar_name = f"{job_name}-{timestamp}"
    prefix = f"{job_name}/{timestamp}"
    with open(f"/tmp/{tar_name}.tar", "wb") as f:
      repo.archive(f, format="tar", prefix=f"{prefix}/")
    repo.head.reset("HEAD~1")
  else:
    sha = git_cmd.rev_parse("HEAD", short=True)
    tar_name = f"{job_name}-{timestamp}"
    prefix = f"{job_name}/{timestamp}"
    with open(f"/tmp/{tar_name}.tar", "wb") as f:
      repo.archive(f, format="tar", prefix=f"{prefix}/")

  archive = tarfile.open(f"/tmp/{tar_name}.tar", "a")
  sbatch_script_name = f"/tmp/{uuid.uuid4().hex}"
  options = {
    "--gres": "gpu:1",
    "--mem": "16G",
    "-c": "4",
    "--account": "rpp-bengioy",
    "--time": "10:00:00",
    "--job-name": f"{job_name}",
  }
  options.update(sbatch_args)
  commands = ["source ~/tf2/bin/activate", " ".join(command)]
  sbatch_script(options, commands, sbatch_script_name, verbose=True)
  archive.add(sbatch_script_name, arcname=f"{prefix}/{exec_path}/sbatch_script.sh")
  archive.close()

  print(f"{tar_name}.tar\t{prefix}/{exec_path}")


if __name__ == "__main__":
  sbatch_args, command = parse_sbatch_args(sys.argv[1:])
  parser = argparse.ArgumentParser()
  parser.add_argument("--job-name", '-J', type=str, required=True,
                      help="name of job")
  args, _ = parser.parse_known_args(sys.argv[1:])
  job_name = args.job_name
  pack(job_name, command, sbatch_args)
