#!/bin/bash

if [ "${BASH_SOURCE[0]:-${(%):-%x}}" -ef "$0" ]
then
    echo "source slurm_tools instead of running it"
    exit 1
fi

DIR=$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")
source "$DIR"/slurm_utils.sh
IFS=$'\n' lines=($(cat "$DIR"/slurm_config))
for line in $lines
do
    cmd=$(echo $line | awk '{ print $1 }')
    alias $cmd="slurm $cmd"
done
